name: Build and Package
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v1

      - name: Lint Go Code
        run: |
          cd chapter12
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          $(go env GOPATH)/bin/golangci-lint run

  list-files:
    name: List Files
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: List Files
        run: |
          cd chapter12
          ls -R
  
  debug-info:
    name: Debug Info
    runs-on: ubuntu-latest
    needs: [ list-files ]
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Debug Info
        run: |
          cd chapter12
          pwd
          make --version
          make build
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ debug-info ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: |
          cd chapter12
          make build